services:
  nginx:
    image: nginx:bmeek
    build: ./requirements/nginx
    container_name: nginx
    ports: [ "443:443" ]
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - net
    depends_on:
      - wordpress
    restart: always

  mariadb:
    image: mariadb:bmeek
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - net
    restart: always

  wordpress:
    image: wordpress:bmeek
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - net
    depends_on :
      - mariadb
    restart: always

networks:
  net:
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/obahi/data/wordpress
      o : bind
      type : none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/obahi/data/mariadb
      o : bind
      type : none

