FROM debian:buster

RUN apt update -y

RUN apt upgrade -y

RUN apt-get install mariadb-server -y

EXPOSE 3306

COPY conf/50-server.cnf	/etc/mysql/mariadb.conf.d/50-server.cnf

COPY ./tools/script.sh /bin/

CMD [ "bash" ,"/bin/script.sh" ]
